# -*- coding: utf-8 -*-
"""Salinan dari Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YhlVWhoB0D7WQOS86YLypkejZeH_kK9S

# Proyek Analisis Data: [Input Bike]
- **Nama:** [Josep Samuel Angelo]
- **Email:** [m009d4ky1905@bangkit.academy]
- **ID Dicoding:** [Input Username]

## Menentukan Pertanyaan Bisnis


*   ### 1. Apakah Perbedaan Musim mempengaruhi peminjaman sepeda ?
*   ### 2.Berapa jumlah pengguna sepeda casual dan register disetiap musim?

## Import Semua Packages/Library yang Digunakan
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
hour_df = pd.read_csv('https://raw.githubusercontent.com/josepsamuel2003/bike/21270d607ad70169420a7809d619a1759f647e0c/hour.csv')
day_df = pd.read_csv('https://raw.githubusercontent.com/josepsamuel2003/bike/21270d607ad70169420a7809d619a1759f647e0c/day.csv')

# Data Cleaning
day_df.rename(columns={'yr': 'year', 'mnth': 'month', 'dteday': 'Date'}, inplace=True)
day_df['Date'] = pd.to_datetime(day_df['Date'])

hour_df.rename(columns={'yr': 'year', 'mnth': 'month', 'dteday': 'Date', 'hr': 'hour'}, inplace=True)
hour_df['Date'] = pd.to_datetime(hour_df['Date'])

# Display data information
st.title('Data Information')
st.write("### Daily DataFrame")
st.write(day_df.info())

st.write("### Hourly DataFrame")
st.write(hour_df.info())

# Analysis of Bike Rentals by Season
st.title('Analysis of Bike Rentals by Season')

# Calculate total bike rentals by season
season_names = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
hour_df['season_name'] = hour_df['season'].map(season_names)
rentals_by_season = hour_df.groupby('season_name')['cnt'].sum()

# Plot rentals by season
st.bar_chart(rentals_by_season)
plt.title('Comparison of Bike Rentals by Season')
plt.xlabel('Season')
plt.ylabel('Number of Rentals')
plt.xticks(rotation=45)
plt.grid(axis='y')
st.pyplot()

# Conclusion
st.markdown("""
**Conclusion:**

Yes, the difference in seasons affects bike rentals. 

*Reasons:*
- Weather: In spring and summer, the weather is usually sunny and warm, motivating people to ride bikes.
- Outdoor Activities: Spring and summer are often associated with more outdoor activities, and biking is a popular choice.
- Holidays: Spring and summer have more holidays, such as Eid al-Fitr and Christmas, which encourage people to bike with family and friends.

""")

# Calculate and visualize the number of casual and registered bike users by season
users_by_season = hour_df.groupby('season_name')['casual', 'registered'].sum()

# Plot users by season
st.bar_chart(users_by_season)
plt.title('Number of Casual and Registered Bike Users by Season')
plt.xlabel('Season')
plt.ylabel('Number of Bike Users')
plt.xticks(rotation=45)
plt.grid(axis='y')
st.pyplot()

# Display user count by season
st.write("**Number of Casual and Registered Bike Users by Season:**")
st.write(users_by_season)
